#!/bin/bash

set -e

printf "Preparando o ambiente"
sleep 1s
printf "."
sleep 1s
printf "."
sleep 1s
printf ".\n"

cd || exit

if [[ ":$PATH:" != *":$HOME/gpush-tool/bin:"* ]]; then
    export PATH="$PATH:~/gpush-tool/bin"
fi

printf "Tudo pronto.\n"
