#!/bin/bash

set -e

printf "Instalando os recursos"
sleep 1s
printf "."
sleep 1s
printf "."
sleep 1s
printf ".\n"

cd || exit

function create_or_update_bash_aliases() {
    local alias_line='
    alias gpush="~/gpush-tool/bin/gpush"'

    if [ ! -f .bash_aliases ]; then
        touch .bash_aliases
    fi

    if ! grep -Fxq "$alias_line" .bash_aliases; then
        echo "$alias_line" >> .bash_aliases
    fi
}

function create_bashrc_if_needed() {
    if [ ! -f .bashrc ]; then
        cat << 'EOF' > .bashrc
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi
EOF
    fi
}

function create_bash_profile_if_needed() {
    if [ ! -f .bash_profile ]; then
        cat << 'EOF' > .bash_profile
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
EOF
    fi
}

function verify_and_setup() {
    create_or_update_bash_aliases
    create_bashrc_if_needed
    create_bash_profile_if_needed

    # shellcheck disable=SC1090
    source ~/.bash_profile
    # shellcheck disable=SC1090
    source ~/.bash_aliases
}

verify_and_setup

printf "Tudo pronto.\n"
